local danger = {
'01. Growing clouds of poisonous gas',
'02. Whispers of the insane dead cause psychic damage',
'03. Acid dripping from the ceiling burns creatures',
'04. Thick fog makes it difficult to see at range',
'05. Quaking ground threatens to knock people prone',
'06. Hallucinogenic gas makes people attack allies',
'07. Hot steam burns creatures more severely each round',
'08. Lightning bolts damage or incapacitate creatures',
'09. Portals vomit forth hordes of minions',
'10. Ghosts of vengeance fill creatures with bloodlust',
'11. Shifting time increases accuracy but decreases defenses',
'12. An unholy presence limits healing',
'13. Arcing electricity hurts those that are close to other creatures',
'14. Arcane lodestones limit magic use',
'15. Icy floors make people slide around Mario style',
'16. Freezing mist damages and slows those within',
'17. Crushing walls close in',
'18. Clouds of bats interrupt casting',
'19. A flood of foul water threatens to drown creatures',
'20. Flammable oil threatens to ignite',
'21. An unholy circle of power that steals life energy',
'22. A skull glyph painted in blood that fills creatures with battle rage',
'23. A summoning circle that spawns minions',
'24. A mystical obelisk that radiates arcane power',
'25. A flaming cauldron that spurts fireballs',
'26. A gargoyle statue that spits poison darts',
'27. A statue of a warrior with a swinging axe trap',
'28. A dragon statue that breathes fire',
'29. Murder holes firing arrows',
'30. Invisible exploding runes on the floor',
'31. A skull on a pike that whispers dark words',
'32. A crystal that fires a beam of burning light',
'33. A pit trap filled with poison sticks',
'34. An area of anti-gravity',
'35. A mirror of entrapment',
'36. Portraits of screaming maidens that drive living creatures mad',
'37. Delicate urns of poison gas',
'38. Serpent statues that spit acid',
'39. Steel rods that fire lightning',
'40. A pillar of black tentacles',
'41. Poisoned dart',
'42. Swinging blade',
'43. Crossbow quarrels',
'44. Spiked pit',
'45. Poisoned gas',
'46. Explosive pots',
'47. Crushing Walls',
'48. Acidic coating',
'49. Exploding rune',
'50. Electrical charge',
'51. Fills with water',
'52. Diseased',
'53. Glyph of madness',
'54. Blinding flash',
'55. Deafening Blast',
'56. Slippery / spiked floor',
'57. Scorching beams',
'58. Trapping mirror',
'59. Demonic possession',
'60. Enervation Ray',
}

return danger

