
local partialS = {
'01. Tu touches ton adversaire mais dans ta précipitation, tu renverse le contenu de ton carquois ou de ton sac',
'02. Tu touches ton adversaire mais ton geste est trop fort, tu perds l\'équilibre et risque de chuter',
'03. Tu touches ton adversaire mais tu as mal dosé ta force, il prend un coup qui le désarçonne mais toi tu entends les os de ton épaule craquer, et tu ressens une forte douleur',
'06. Tu lances si violemment que l’anse de ton sac craque et qu’il tombe lourdement sur le sol',
'07. Tu lances si violemment que l’anse de ton sac craque et que son contenu se répand en roulant et cliquetant à des mètres à la ronde',
'09. Tu touches ton adversaire mais ta sueur (ou ton sang) t’aveuglent l’espace d’un instant',
'10. Tu touches ton adversaire en poussant un tel cri involontaire, que l’assistance proche se retourne vers toi et te scrute soudainement',
'11. Tu touches ton adversaire mais ton élan est trop fort, et tu pars en avant sans controler ton mouvement, jusqu’à te cogner contre un obstacle ou un compagnon',
'12. Tu touches ton adversaire mais, si le coup ne l’as pas tué, maintenant tu l’as mis en rage',
'14. Tu touches ton adversaire et il pousse un tel cri de douleur qu’il fige les adversaires alentour, qui maintenant t’on mis en joue',
'15. Tu touches ton adversaire si violemment que la force du coup te fait tomber à la renverse',
'17. Tu touches ton adversaire, mais même blessé il pousse un rire qui galvanise les adversaires',
'18. Tu touches ton adversaire mais le choc te fait perdre ton arme qui tombe à terre',
'21. Tu touches ton adversaire qui recule lourdement, mais il te cachait un autre acolyte qui surgit et te tombe dessus en furie',
'22. Tu touches ton adversaire avec tellement de fougue que tu n’as pas vu que lui, dans le meme temps, a pointé une dague de lancer visant ta gorge',
'23. Tu touches ton adversaire mais, en le suivant dans ses déplacements, vous vous éloignez de la zone de combat et vous retrouvez maintenant un peu isolés',
'24. Tu touches mais mal, tes vêtements se prennent dans un obstacle et ils se déchirent violemment, tu es à moitié nu maintenant',
'24. Tu touches mais mal, tu es déséquilibré et tu tombes sur un piège à proximité',
'25. Tu touches mais le choc est trop important, ton arme se tord…',
'26. Tu touches mais le choc est trop important, tu titubes en reculant, le nez en sang',
'28. Tu touches mais tu entends les cris d’autres adversaires qui arrivent, non loin de là',
'29. Tu touches mais tu réalises que ton adversaire t’as entrainé un peu trop loin et tu commences à être encerclé maintenant',
'30. Tu touches mais tu comprends qu’il faut, soit retenir ton coup (degats/2), soit aller jusqu’au bout mais ton adversaire va s’écrouler sur un de tes compagnons',
'31. Tu touches mais tu comprends qu’il faut, soit retenir ton coup (degats/2), soit te laisser aller en avant mais risquer de t’affaler de tout ton long',
'32. Tu touches mais tu comprends qu’il faut, soit dévier ton coup (degats/2), soit risquer de blesser un compagnon tellement ton geste est puissant et incontrolé',
'33. Tu touches mais tu comprends qu’il faut, soit retenir ton coup (degats/2), soit subir une contre attaque dangereuse car ton adversaire cherchait une faille pendant tout ce temps',
'34. Tu touches mais tu comprends qu’il faut, soit faire un mouvement de coté (degats/2), soit subir une attaque à distance de plusieurs archers restés en arrière',
'36. Tu touches mais tu comprends qu’il faut, soit retenir ton coup (degats/2), soit glisser et risquer de tomber au sol non loin d\'un adversaire',
'37. Tu touches mais tu dois choisir entre retenir ton coup (degats/2), soit lâcher ton sac',
'38. Tu touches mais tu dois choisir entre porter ton coup à pleine force, soit porter secours à un allié proche mais dégats/2',
'39. Tu touches mais tu dois choisir entre porter ton coup à pleine force et endommager une de tes pièces d’armure, soit retenir ton coup (degats/2)',
'41. Tu touches mais ton élan t\'entraine à chuter au beau milieu de la bataille',
'42. Tu touches mais ton élan t\'entraine à chuter au beau milieu d’adversaires enragés',
'43. Tu touches mais les cris de ton infortuné adversaire semblent attirer les cris d’une autre bête, plus puissante semble-t-il',
'44. Tu touches mais les cris de ton infortuné adversaire semblent déclencher des bruits de tambour à proximité',
'45. Tu touches mais à mesure qu\'il extirpe le projectile, les yeux de ton adversaire se révulsent et il psalmodie une puissante incantation…',
'46. Tu touches mais à mesure qu\'il extirpe le projectile, tu vois une bête jaillir sur son épaule et s’abattre sur toi',
'47. Tu touches si violemment que ton adversaire cogne un élément de décor, au point de le faire tomber ou écrouler…',
'48. Tu touches mais au même moment, tu entrevois le liquide visqueux et empoisonné qui imprègne l\'arme de ton adversaire…',
'49. Tu touches mais au même moment, tu entrevois les runes magiques que ton adversaire porte sur son visage, ses bras et son torse',
'50. Tu touches mais au même moment, tu entends les incantations magiques que quelqu’un psalmodie derrière les lignes ennemies',
'51. Tu touches mais au même moment, tu entrevois un autre adversaire surgir de l’obscurité et se jeter sur toi, dans ton angle de vision',
'52. Tu touches mais au même moment, tu ressens une crampe ou un claquage, et tu te figes en grimaçant',
'54. Tu touches mais au même moment, tu entends le souffle d’un autre adversaire qui vient de se glisser discrètement dans ton dos',
'55. Tu touches mais tu entends le claquement d’un mécanisme et d’une flêche qui jaillit du bras de ton adversaire, tout prêt de ton visage',
'56. Tu touches mais la sueur coule dans ta main, et ton arme glisse de tes mains',
'57. Tu touches mais la sueur coule dans tes sourcils et sur tes yeux qui te brulent, tu commences à voir flou et tu dois reculer',
'58. Tu touches mais ton casque glisse et se retrouve de guinguois, il te masque un oeil maintenant',
'59. Tu touches mais la lanière de ton casque se détache et ton casque roule lourdement sur le sol',
'60. Tu touches mais la lanière de ta sandale se détache et ta chaussure disparait au loin, tu es déséquilibré et à moitié pied nu',
'62. Tu touches mais, si tu étais resté discret ou caché jusque là, tu es maintenant en pleine lumière',
'63. Tu touches mais, si tu étais resté discret ou caché jusque là, tu réalises avec effroi que tu n’étais pas le seul à t’être glissé dans cette cachette, un adversaire jaillit près de toi',
'64. Tu touches mais ton adversaire te jette au visage, dans un geste de défense, un sac plein d’affaires bringuebalantes, tu es désarçonné ',
'65. Tu touches mais la violence du tir te vrille le bras, tu as mal maintenant',
'66. Tu touches mais un élément de vetement (manche, cape, chaussure) reste coincé dans un élément de décor, tu dois prendre une décision sur quoi faire',
'68. Tu touches mais tu réalises à ce moment que tu n’avais pas bien jaugé ton adversaire, maintenant tu vois clairement qu’il a une Mutation (table ci dessous)',
'69. Tu touches ton adversaire qui recule et est sur le point de tomber dans un piège ! Seulement voilà, s’il se déclenche le piège est tout aussi dangereux pour toi !',
'72. Tu touches mais ton geste est trop brutal et tu cognes violemment un compagnon, vous voilà méchamment sonnés tous les deux',
'73. Tu touches ton adversaire mais tu comprends qu’il doit être drogué, il ne semble pas ressentir la douleur et son regard est fou',
'75. Tu touches violemment mais tu entends des objets fragiles se casser (ou se déchirer) dans ton sac',
'76. Tu touches mais la violence du coup te projette sur un compagnon, dont tu viens d’écraser le sac dans un bruit de casse ou de déchirure',
'77. Tu touches ton adversaire mais tu entends le clinquement de toutes tes pièces d’or qui tombent et roulent sur le sol à vos pieds',
'80. Tu touches mais tu te replaces mal et ton adversaire jette un projectile vers toi, , que fais-tu ?',
'81. Tu touches mais tu te replaces mal et ton adversaire jette son bouclier contre ton visage, que fais-tu ?',
'82. Tu touches mais tu te replaces mal et ton adversaire va tirer dans ta direction, que fais-tu ?',
'83. Tu touches mais tu te replaces mal et ton adversaire a disparu de ton champ de vision lorsque tu tournes la tête, que fais tu ?',
'84. Tu touches mais tu te replaces mal et ton adversaire se jette sur toi pour te renverser, que fais tu ?',
'85. Tu touches mais ton adversaire a eu le temps de sortir une hache de jet, qu’il jette de toutes ses forces sur toi, que fais tu ?',
'86. Tu touches mais ton adversaire se jette tête baissée sur toi, et tu réalises soudain à quoi sert la pointe métallique. Que fais tu ?',
'88. Tu touches mais tu entrapercois un lourd objet (bloc, tronc, pierre, métal) venir s’écraser sur toi / vous depuis le fond de la scène. Que fais tu ?',
'89. Tu touches mais ton adversaire vient au contact et cherche à te renverser, que fais tu ?',
'92. Tu touches mais ton adversaire a le temps de reculer et de te lancer une lame vers le torse, que fais tu ?',
'95. Tu touches mais au moment où tu retires ta lame, tu entends les flèches filer vers toi, elles ne t’épargneront ni toi ni ton infortuné adversaire',
'00. Au moment où tu touches, tu comprends que tu viens de t’en prendre à un être possédé par une entité démoniaque',
}

return partialS

