local trait = {

"01. Vieux et hideux, mais tout en muscles",
"02. Borgne, l'oeil manquant est traversé d'une horrible cicatrice comme un gros X",
"03. Au sourire horrible, car sa bouche à jadis été taillée par une lame et mal recousue",
"05. Il lui manque une oreille, mais il semble avoir mis un postiche, une fausse oreille de porc",
"06. Borgne, mais il a remplacé l'oeil manquant par une boule de fer rouillée",
"07. Quand il tourne la tête on voit attachés au bout de ses sales cheveux des doigts coupés virevoltant",
"08. Porte plusieurs colliers de dents",
"09. S'est cousu des cheveux qui ne sont pas à lui",
"10. Les yeux sont vitreux mais il semble y voir clair",
"11. Manchot",
"12. Manchot mais a remplacé son avant bras par une patte animale",
"13. Porte une pointe de lance rouillée qui lui traverse le crâne jusqu'à sortir par une joue, mais qui n'a pas l'air de le gêner plus que ça",
"14. Yeux et bouches sont rougies de sang",
"15. Gros et gras, sa graisse frissonne au moindre mouvement",
"16. Squelettique mais vif",
"17. Pratiquement nu, seuls ses parties sont masquées par un tissu noirâtre",
"18. Porte un masque horrible et grimaçant",
"19. Des oreilles et plusieurs de ses doigts sont coupés",
"20. Porte un sifflet autour du cou, au milieu de colliers grotesques",
"21. Porte une couronne de métal, grotesque sur une tête comme la sienne",
"22. Une partie - étonnamment étendue - de son crâne est enfoncée",
"23. Sa chair est à vif sur ses bras et son torse",
"24. Sa bouche est cousue, sans doute à t'il désobéi un peu trop",
"25. Porte un carquois et des gants d'elfes, grotesques sur lui",
"26. Porte une tunique de soie trop belle et trop grande sur lui",
"27. Porte une cote de mailles naine, mais visiblement à l'envers",
"28. Au corps émacié sauf son ventre protubérant, sans doute malade",
"29. Une protubérance énorme dans son cou",
"30. Porte un casque grotesque orné de plumes",
"31. Porte un masque de peau sans doute humaine",
"32. N'a pas de mains mais deux épées sont solidement attachées a ses avant bras",
"33. Ses crocs sont énormes et taillées en pointes",
"34. Porte un maquillage de cendres qui lui donne l'air d'un cadavre",
"35. Porte des gantelets de fer trop grand pour lui",
"36. Sur chaque épaule une longue pointe, sur chaque une tête encore pourrissante",
"37. Horrible albinos",
"38. Oreilles énorme, tombante, pleine de boucles et d'objets métalliques",
"39. Tient attachés par une sangle à sa ceinture, deux minuscules porcs grognards",
"40. Plus de jointures à ses bras et ses jambes que la normale",
"41. Porte des cornes sur le crâne",
"42. Nombreux body piercing",
"43. N'a pratiquement plus de dents et les restantes sont horriblement gâtées, mais regarde toujours de face avec un horrible sourire",
"44. Porte de ridicules colliers et bracelets de queues de rongeurs",
"45. Qui tremble horriblement, on ne sait pas si c'est le froid ou des spasmes",
"46. Porte d'horribles cicatrices sur tout le corps",
"47. Manque ses deux oreilles",
"48. Une jambe difforme, marche péniblement et en boitant",
"49. Chien en laisse",
"50. Le visage rongé par la maladie",
"51. Porteur de la peste, sans doute",
"52. Le nez n'est qu'un horrible trou béant",
"53. Une joue trouée, on voit une rangée de dents pourries",
"54. Les yeux ne sont pas symétrique, le visage est horriblement dérangeant",
"54. Bossu et courbé, mais l'oeil vif on dirait",
"55. Nerveux et en alerte",
"56. Un œil abîmé, mais respire et renifle sans arrêt, comme la truffe d'un chien",
"57. Ses doigts sont difformes et malades",
"58. Porte un accoutrement de vêtements humains de belle facture",
"59. Porte des bagues et bracelets elfique, y compris sur les orteils noirs et sales",
"60. Porte un collier de clochettes et au bout de ses longues oreilles sales, qui tintent doucement au moindre mouvement",
"61. Crache sur le sol, sans arrêt, de longs filets de bave rougeâtre",
"62. La mâchoire est cachée par un masque de fer",
"63. Porte un beau casque de Paladin, mais sale et fendu",
"64. Énorme cicatrice sur le crâne dégarni, a subi une trépanation",
"65. Porte dans son sac, des crânes humains qui s'entrechoquent",
"66. Porte attachées sur le torse, d'horribles poupées de chiffon percées de lames et de clous",
"67. Porte des parchemins qu'il ne sait pas déchiffrer",
"68. Louche terriblement",
"69. La moitié du visage est figée dans une grimace horrible, le reste n'est guère mieux",
"70. Porte des bocaux de doigts et d'yeux, et un bric à brac à la ceinture",
"71. Porte des serpents en guise de colliers",
"72. L'air endormi, mais sursaute au moindre son",
"73. L'air plus jeune, mais au sourire horriblement carnassier",
"74. Scarification sur le visage et les bras",
"75. Porte ce qui pourrait être une écaille de dragon sur le torse, on se demande comment ça s'est retrouvé là",
"76. Porte une belle chemise autrefois blanche, mais avec un énorme trou au milieu du torse",
"77. Une main difforme et pendante, trop grande par rapport au reste du corps",
"78. Vieux et maigre, mais un terrible regard",
"79. Porte un autre compère sur son dos",
"80. Des bandages sales autour du crâne",
"81. Porte une seule sandale, l'autre pied est trop gros pour rentrer",
"82. Un mucus verdâtre coule de son nez, et de ses yeux",
"83. Ses ongles de mains et des pieds sont de vraies griffes, qu'il a l'air d'entretenir comme telles",
"84. Semble ne pas avoir eu le temps de se rabiller correctement",
"85. Un faux visage, grotesque, est peint à l'arrière de son crâne",
"86. Porte un diadème de belle facture, mais visiblement pour une dame",
"87. Porte une cote de mailles trouée et trop courte sur son long torse",
"88. Un bras atrophié",
"89. Porte un beau casque elfique, mais une pointe de flèche encore plantée dedans",
"90. Le corps et la peau totalement noirs",
"91. Un œil fermé et gonflé, comme s'il s'était battu récemment",
"92. Porte des morceaux d'armure de plaque, bringuebalants, qui ne protège guère...",
"93. Une belle cape rouge mais dont le bas est crasseux, boueux voire pire",
"94. Porte plusieurs sacs sur le dos, qui ont l'air léger mais encombrants",
"95. Porte une gamelle, du bois et une petite cage attachés dans le dos",
"96. Massif et impressionnant",
"97. Les mâchoires larges et carré, l'air dur",
"98. Des yeux furtif, tout le temps à scruter",
"99. Le corps noueux et musclé",
"100. Un bandage crasseux sur son épaule droite",
"101. Porte plusieurs couteaux de jet à sa ceinture",
"102. Appuyé sur une longue lance aux multiples piquants",
"103. Tient un marteau de mauvaise facture dans chaque main",
"104. Porte un beau marteau de fabrication naine au côté",
"105. Derrière un grand bouclier aux décorations chargées et bestiales",
"105. Derrière un grand bouclier brillant",
"106. Porte une multitude de colliers, bracelets, plumes et colifichets",
"107. Porte des colliers de ce qui ressemble à des crânes de rongeurs",
"108. Un étrange corbeau sur l'épaule",
"109. Porte un petit tambour au côté",
"110. Un visage atrocement maigre et creusé",
"111. Porte un grand Cor au côté",
"112. Porte un long baton et des tissus, de ce qui pourrait être un étendard",
"113. Tient un deuxième compère au bout d'une chaîne",
"114. Un grand nez long et crochu",
"115. Des lèvres constamment retroussées, sur un rictus horrible",
"116. Plusieurs grosses cicatrices sur le front et les joues",
"117. Porte un casque tellement abîmé qu'il ne protège plus du tout le haut du crâne",
"118. Des jambes maigres sur un gros corps",
"119. Porte des fagots de bois et une petite hache",
"120. Porte un grand hachoir taché",
"121. Une épée recourbée dans chaque main",
"122. Des peintures de guerres sinistres sur tout le corps",
"123. Torse nu, affreux et recouvert de peinture rouge",
"124. Porte des fioles, des tiges et des herbes, et un vieux livre",
"125. Se tient sur une longue canne de bois, noueuse et surmontée d'une pierre laiteuse",
"126. Porte du petit gibier attaché au côté",
"127. Porte plusieurs petits sacs et ce qui ressemble à un piège à loup",
"128. Porte plusieurs sacs horriblement tachés, des gouttes de sang semblent goutter de l'un d'entre eux",
"129. Porte un bel arc elfique au côté",
"130. Porte un arc grossier et des flèches aux plumes noires et sinistres",

}

return trait

